In [ ]:
"""
Questions to be Answered 

1. How manysales have tehy made with amounts more than 1000
2. how many sales have they made that belong to the Category 'Tags' and have a Quantity of 3
3. The total sales by Category 
4. Average Amount by Category and Status
5. Total Series vy Fullfillment and Shipment Type 
6. Export dataFrames created in 4 and 5 to excel
"""

"\nQuestions to be Answered \n\n1. How manysales have tehy made with amounts more than 1000\n2. how many sales have they made that belong to the Category 'Tags' and have a Quantity of 3\n3. The total sales by Category \n4. Average Amount by Category and Status\n5. Total Series vy Fullfillment and Shipment Type \n\n"

In [22]:
import pandas as pd

In [72]:
sales_data = pd.read_excel("sales_data.xlsx", index_col='index')

EXPLORING THE DATA

In [24]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128975 entries, 0 to 128974
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  currency            121180 non-null  object
 14  Amount              121180 non-null  float64
 15  ship-city           128942 non-null  object
 16  ship-state          128935 non-null  object
 17  ship-postal-code    128935 non-null  float64
 18  ship-country        128935 non-null  object
 19  promotion-ids       79815 non-null   object
 20  B2B                 128968 non-null  float64
 21  fulfilled-by        39276 non-null   object
dtypes: float64(3), int64(1), object(18)
memory usage: 22.6+ MB

In [25]:
sales_data.describe()

                 Qty         Amount  ship-postal-code            B2B
count  128975.000000  121180.000000     128935.000000  128968.000000
mean        0.904431     648.561465     463963.108256       0.006754
std         0.313354     281.211687     191475.865632       0.081903
min         0.000000       0.000000     110001.000000       0.000000
25%         1.000000     449.000000     382421.000000       0.000000
50%         1.000000     605.000000     500033.000000       0.000000
75%         1.000000     788.000000     600024.000000       0.000000
max        15.000000    5584.000000     989898.000000       1.000000

In [26]:
sales_data['Amount'].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [27]:
print(sales_data.columns)

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [28]:
sales_data.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
index,,,,,,,,,,,,,,,,,,,,,
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,0.0,Easy Ship
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,Blouse,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,0.0,Easy Ship
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,Blouse,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,1.0,NaN
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,0.0,Easy Ship
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,0.0,NaN

In [29]:
print(sales_data.head())

                  Order ID      Date                        Status Fulfilment  \
index
0      405-8078784-5731545  04-30-22                     Cancelled   Merchant
1      171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer   Merchant
2      404-0687676-7273146  04-30-22                       Shipped     Amazon
3      403-9615377-8133951  04-30-22                     Cancelled   Merchant
4      407-1069790-7240320  04-30-22                       Shipped     Amazon

      Sales Channel  ship-service-level    Style              SKU Category  \
index
0          Amazon.in           Standard   SET389   SET389-KR-NP-S      Set
1          Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL   Blouse
2          Amazon.in          Expedited  JNE3371    JNE3371-KR-XL   Blouse
3          Amazon.in           Standard    J0341       J0341-DR-L    Dress
4          Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL      Top

      Size  ... Qty currency  Amount    ship-city   ship-state  \
index       ...
0        S  ...   0      INR  647.62       MUMBAI  MAHARASHTRA
1      3XL  ...   1      INR  406.00    BENGALURU    KARNATAKA
2       XL  ...   1      INR  329.00  NAVI MUMBAI  MAHARASHTRA
3        L  ...   0      INR  753.33   PUDUCHERRY   PUDUCHERRY
4      3XL  ...   1      INR  574.00      CHENNAI   TAMIL NADU

      ship-postal-code ship-country  \
index
0             400081.0           IN
1             560085.0           IN
2             410210.0           IN
3             605008.0           IN
4             600073.0           IN

                                           promotion-ids  B2B fulfilled-by
index
0                                                    NaN  0.0    Easy Ship
1      Amazon PLCC Free-Financing Universal Merchant ...  0.0    Easy Ship
2           IN Core Free Shipping 2015/04/08 23-48-5-108  1.0          NaN
3                                                    NaN  0.0    Easy Ship
4                                                    NaN  0.0          NaN

[5 rows x 22 columns]

In [30]:
sales_data.dtypes

Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                   float64
fulfilled-by           object
dtype: object

CLEANING THE DATA

In [31]:
# check for missing data in our dataframe

sales_data.isnull()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
index,,,,,,,,,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
128971,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
128972,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
128973,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
128974,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [32]:
# check total sum of null values in our dataframe

sales_data.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               40
ship-postal-code         40
ship-country             40
promotion-ids         49160
B2B                       7
fulfilled-by          89699
dtype: int64

In [33]:
# drop any rows that have null values. Because we are not sure of the results, let's not mess with the current df and create a new one to mess with.

sales_data_dropped = sales_data.dropna()

In [34]:
# the previous dropped too many amounts. now we will only drop those with missing data from one column - the 'amounts' column. 

sales_data_cleaned = sales_data.dropna(subset = ['Amount'])

In [35]:
print(sales_data_cleaned.isnull().sum())

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         5136
Qty                       0
currency                  0
Amount                    0
ship-city                31
ship-state               38
ship-postal-code         38
ship-country             38
promotion-ids         41705
B2B                       7
fulfilled-by          83640
dtype: int64

SLICING AND FILTERING DATA

In [36]:
""" 1. How manysales have tehy made with amounts more than 1000 """

high_amount_sales = sales_data_cleaned[sales_data_cleaned['Amount'] > 1000]

In [37]:
"""
# Delete a specific variable from Jupyter Variables window
del variable_name

# Delete multiple variables from Jupyter Variables window
del var1, var2

# Delete all variables (except special ones) from Jupyter Variables window
%reset -f
"""

'\n# Delete a specific variable from Jupyter Variables window\ndel variable_name\n\n# Delete multiple variables from Jupyter Variables window\ndel var1, var2\n\n# Delete all variables (except special ones) from Jupyter Variables window\n%reset -f\n'

In [38]:

# selecting a subset from the column category 
category_data = sales_data_cleaned[sales_data_cleaned['Category'] == 'Top']

In [39]:
""" 2. how many sales have they made that belong to the Category 'Tags' and have a Quantity of 3 """
# Selecting a subset from the data based on multiple conditions
filtered_data = sales_data_cleaned[(sales_data_cleaned['Category'] == 'Top') & (sales_data_cleaned['Qty'] == 3)]

AGGREGATING DATA

In [45]:
""""" 3. The total sales by Category """""

category_totals = sales_data_cleaned.groupby('Category', as_index=False)['Amount'].sum()
category_totals = category_totals.sort_values('Amount', ascending=False)

In [ ]:
"""4. Average Amount by Category and Fulfilment"""
fulfilment_averages = sales_data_cleaned.groupby(['Category', 'Fulfilment'], as_index=False)['Amount'].mean().round(2)
fulfilment_averages = fulfilment_averages.sort_values('Amount', ascending=False)

In [69]:
"""4a. Average Amount by Category and status"""
status_averages = sales_data_cleaned.groupby(['Category', 'Status'], as_index=False)['Amount'].mean().round(2)
status_averages = status_averages.sort_values('Amount', ascending=False)

In [ ]:
"""5. Total Sales by Fullfillment and Shipment Type"""
shipment_and_Fulfilment_totals = sales_data_cleaned.groupby(['Shipment', 'Fulfilment'], as_index=False)['Amount'].sum().round(2)
shipment_and_Fulfilment_totals  = shipment_and_Fulfilment_totals .sort_values('Amount', ascending=False)
# the shipment column does not exist.

KeyError: 'Shipment'

In [ ]:
#  Let's see what other column we can use. Let's use courier status

sales_data_cleaned.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='object')

In [ ]:
"""5a. Total Sales by Fullfillment and Shipment"""
shipment_and_Fulfilment_totals = sales_data_cleaned.groupby(['Fulfilment', 'Courier Status'], as_index=False)['Amount'].sum().round(2)
shipment_and_Fulfilment_totals = shipment_and_Fulfilment_totals.sort_values('Amount', ascending=False)
""" change the column name courier status to shipment"""
shipment_and_Fulfilment_totals.rename(columns ={'Courier Status': 'Shipment'}, inplace=True) # we do not need to reassign the variable by using '='

EXPORTING THE DATA

In [82]:
"""6. Export dataFrames created in 4 and 5a to excel"""

status_averages.to_excel('average_sales_by_cat_&_stat.xlsx', index=False)
shipment_and_Fulfilment_totals.to_excel('sales_by_Fullfillment_and_Shipment.xlsx', index=False)